export class loader {
    constructor(params={}) {
        var me = this;
        var main, loading, curwait;
        this.init = function () {
            //ajoute le loader à la page
            let html = `
            <style>
#loading-container{
	position: fixed;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
	z-index:99999;
}
#ws-loading{
	background-image: url('assets/img/logo-paragraphe-blanc.svg');
    background-repeat: no-repeat;
    background-size: contain;
    background-position-y: center;
}

@keyframes ldio-81lvt7kt8nr {
	0% { transform: rotate(0deg) }
	50% { transform: rotate(180deg) }
	100% { transform: rotate(360deg) }
}
.ldio-81lvt7kt8nr div {
	position: absolute;
	animation: ldio-81lvt7kt8nr 1s linear infinite;
	width: 136px;
	height: 136px;
	top: 32px;
	left: 32px;
	border-radius: 50%;
	box-shadow: 0 4px 0 0 #84494d;
	transform-origin: 68px 70px;
}
.loadingio-spinner-eclipse-tkisngtn2 {
	width: 200px;
	height: 200px;
	display: inline-block;
	overflow: hidden;
	background: #ffffff;
}
.ldio-81lvt7kt8nr {
	width: 100%;
	height: 100%;
	position: relative;
	transform: translateZ(0) scale(1);
	backface-visibility: hidden;
	transform-origin: 0 0; /* see note above */
}
.ldio-81lvt7kt8nr div { box-sizing: content-box; }
/* generated by https://loading.io/ */

/* WS loader */
@keyframes ldio-6pd26u1x99x {
	0% { transform: rotate(0) }
	100% { transform: rotate(360deg) }
}
.ldio-6pd26u1x99x div { box-sizing: border-box!important }
.ldio-6pd26u1x99x > div {
	position: absolute;
	width: 146.88px;
	height: 146.88px;
	top: 28.560000000000002px;
	left: 28.560000000000002px;
	border-radius: 50%;
	border: 4.08px solid #000;
	border-color: #ffffff transparent #ffffff transparent;
	animation: ldio-6pd26u1x99x 1.8518518518518516s linear infinite;
}

.ldio-6pd26u1x99x > div:nth-child(2), .ldio-6pd26u1x99x > div:nth-child(4) {
	width: 134.64000000000001px;
	height: 134.64000000000001px;
	top: 34.68px;
	left: 34.68px;
	animation: ldio-6pd26u1x99x 1.8518518518518516s linear infinite reverse;
}
.ldio-6pd26u1x99x > div:nth-child(2) {
	border-color: transparent #c2000b transparent #c2000b
}
.ldio-6pd26u1x99x > div:nth-child(3) { border-color: transparent }
.ldio-6pd26u1x99x > div:nth-child(3) div {
	position: absolute;
	width: 100%;
	height: 100%;
	transform: rotate(45deg);
}
.ldio-6pd26u1x99x > div:nth-child(3) div:before, .ldio-6pd26u1x99x > div:nth-child(3) div:after {
	content: "";
	display: block;
	position: absolute;
	width: 4.08px;
	height: 4.08px;
	top: -4.08px;
	left: 67.32000000000001px;
	background: #ffffff;
	border-radius: 50%;
	box-shadow: 0 142.8px 0 0 #ffffff;
}
.ldio-6pd26u1x99x > div:nth-child(3) div:after {
	left: -4.08px;
	top: 67.32000000000001px;
	box-shadow: 142.8px 0 0 0 #ffffff;
}

.ldio-6pd26u1x99x > div:nth-child(4) { border-color: transparent; }
.ldio-6pd26u1x99x > div:nth-child(4) div {
	position: absolute;
	width: 100%;
	height: 100%;
	transform: rotate(45deg);
}
.ldio-6pd26u1x99x > div:nth-child(4) div:before, .ldio-6pd26u1x99x > div:nth-child(4) div:after {
	content: "";
	display: block;
	position: absolute;
	width: 4.08px;
	height: 4.08px;
	top: -4.08px;
	left: 61.2px;
	background: #c2000b;
	border-radius: 50%;
	box-shadow: 0 130.56px 0 0 #c2000b;
}
.ldio-6pd26u1x99x > div:nth-child(4) div:after {
	left: -4.08px;
	top: 61.2px;
	box-shadow: 130.56px 0 0 0 #c2000b;
}
.loadingio-spinner-double-ring-4dols36ufwg {
	width: 204px;
	height: 204px;
	display: inline-block;
	overflow: hidden;
	background: none;
}
.ldio-6pd26u1x99x {
	width: 100%;
	height: 100%;
	position: relative;
	transform: translateZ(0) scale(1);
	backface-visibility: hidden;
	transform-origin: 0 0; /* see note above */
}
.ldio-6pd26u1x99x div { box-sizing: content-box; }
/* generated by https://loading.io/ */            
            </style>
            <div class="loadingio-spinner-double-ring-4dols36ufwg" id="ws-loading">
                <div class="ldio-6pd26u1x99x" id="ws-animation">
                    <div></div>
                    <div></div>
                    <div>
                        <div></div>
                    </div>
                    <div>
                        <div></div>
                    </div>
                </div>
            </div>
            `;
            d3.select('#loading-container').remove();
            main = d3.select('body').append('div')
                .attr('id','loading-container').attr('tabindex',-1);
            main.html(html);
            loading = main.select("#ws-loading");
            me.hide(true);
        }
                
        this.show = async function(){
            while (!loading.node().checkVisibility()) {
                console.log("loading "+curwait);
                loading.style("display", "inline-block");
            }
            console.log("loaded "+curwait);
            return curwait ++;
            /*
            waitForElement("#ws-loading", 3000).then(function(){
                console.log("loading load "+curwait);
                return curwait ++;
            }).catch(()=>{
                console.log("loading did not load in 3 seconds");
            });
            await setTimeout(function(){
                curwait ++;
            }, 1000);
            return curwait;
            */
        }
        this.hide = function(all=false){
            if(all)curwait=0;
            curwait --;
            if(curwait<1){
                loading.style("display", "none");
                curwait=0;
                console.log("loading hide "+curwait);
            }       
        }

        /** thanks to https://stackoverflow.com/questions/3992787/how-to-wait-for-an-element-to-exist-in-the-dom-before-running-code
         * Wait for an element before resolving a promise
         * @param {String} querySelector - Selector of element to wait for
         * @param {Integer} timeout - Milliseconds to wait before timing out, or 0 for no timeout              
         */
        function waitForElement(querySelector, timeout){
            return new Promise((resolve, reject)=>{
                var timer = false;
                if(document.querySelector(querySelector)) return resolve();
                const observer = new MutationObserver(()=>{
                if(document.querySelector(querySelector)){
                    observer.disconnect();
                    if(timer !== false) clearTimeout(timer);
                    return resolve();
                }
                });
                observer.observe(document.body, {
                childList: true, 
                subtree: true
                });
                if(timeout) timer = setTimeout(()=>{
                observer.disconnect();
                reject();
                }, timeout);
            });
        }

        this.init();
    }
}
