---
title: "Intégration efficace d'un document - Gestion numérique d'un laboratoire"
format: html
---

# Intégration efficace d'un document selon les codes du WEB

## Introduction

Durant le processus de mise à jour et/ou de maintien à flot du site web, le stagiaire pourra être amené à intégrer certains documents au site web pour diverses raisons : affichage à la vue de tous, informations pouvant servir à la maintenance du site, ... Cependant, ces documents ne sont souvent pas structurés correctement pour une exploitation efficace par un navigateur. Tout un processus de rééditorialisation du document est donc nécessaire pour l'adapter aux règles de lecture et de navigation du web.

A titre d'exemple, lors du stage ayant servi à la rédaction de ce corpus protocolaire, il fut demandé l'éditorisalisation web du dernier rapport HCERES émis par le laboratoire, afin de pouvoir en exploiter les nombreuses informations liées au laboratoire (informations générales sur le laboratoire, informations sur des projets en cours ou réalisés, ...) pour effectuer des mises à jour ou des publications d'articles.

Ci-dessous quelques lignes de protocole et quelques conseils sur le processus d'éditorialisation d'un document.

**Durée** : 
- à mettre en place : MODEREE (dépend de la taille du document principalement)

## Travail de structuration du document

### D'abord, du repérage

La première tâche **à absolument effectuer** est un **repérage approfondi du document**, avec pour objectif de s'imprégner de sa structure et ainsi pouvoir se projeter sur la façon d'intégrer efficacement le document sur le web. Si cette étape est négligée, le processus d'éditorialisation du document sera certainement peu optimisé et le résultat final très certainement mal implémenté et/ou peu convaincant.

**Comment s'y prendre :**
La meilleure façon d'effectuer ce repérage est repasser plusieurs fois dessus, en repérant d'abord les éléments généraux sur la structure *(1)*, puis d'affiner l'analyse progressivement *(2)* jusqu'à arriver à la signification visuelle des plus petits éléments *(3)*.

1. La première étape, celle du relevage des éléments généraux, va permettre deux choses : comprendre de quoi parle le document et visualiser comment le découper par la suite en fonction des diverses parties. A ce niveau, après avoir survolé une première fois le document, s'il s'agit d'un document issu d'un traitement de texte (PDF, *Word*, *Sheets*, ...) et que celui-ci a bien été structuré en amont, il est possible de se fier à la *table des matières* insérée dans le document ou fournie par votre logiciel (référencant les divers niveaux de titrage).

[insérer exemple avec rapport HCERES, découpé en quatre grande parties]

2. Une fois les grands axes du document déterminés, il est possible de passer à la seconde étape, soit celle où l'analyse s'approfondie. A ce niveau, il s'agit de traiter des divers plus petits niveaux de titrage (jusqu'à ceux n'apparaissant pas forcément dans la table des matières). Cette étape permet par ailleurs de s'imprégner plus en profondeur du document, ce qui peut déjà permettre quelques remodelage de la structure déjà définie.

[insérer exemple avec rapport HCERES]

3. Enfin, une fois la structure globalement analysée, nous arrivons à l'analyse des différents choix typographique. Il est très probable que pendant le repérage vous avez vu des zones en **gras**, en *italique*, avec une police plus ou moins grosse, etc... Cette étape consiste donc à revenir sur ces zones typographiquement différentes pour tenter de comprendre la signification (référence bibliographique, information importante, ...) puis de se demander comment l'information mise en valeur par la typopgraphie peut être retranscrite ensuite sur le web.

[insérer exemple avec rapport HCERES]

### Ensuite, une première implémentation

NOTE : Il est vivement conseillé de lire la [documentation sur SPIP](../tools/intro_spip.qmd) avant d'aller plus loin.

Création des rubriques / sous-rubriques / articles
Implémentation (à base de copier-coller) du textes dans les articles correspondant
Intégration des divers éléments de style repérés précédemment

### Enfin, l'adapter aux codes du web
Comme déjà évoqué lors de l'[étape de mise à jour du site](/web/site_web.qmd), l'adaptation du document récemment importé aux codes du web est primordial pour son utilisation. 

hypertextualisation, recoupage en plusieurs articles, ...
NOTE conseil : Conserver une trace complète du document importée dans le site, c'est-à-dire création de nouveaux articles à chaque fois