---
title: "Gérer le site web - Gestion numérique d'un laboratoire"
format: html
---

# Maintenir à jour le site internet du laboratoire

## Introduction

Absolument indispensable de nos jours pour toute organisation, le site web est un incontournable pour assurer sa communication qu'il est important de ne pas négliger. En effet, celui-ci constitue une véritable vitrine des activités du laboratoire où donc, la plupart du temps, le public se fera un premier opinion vis-à-vis de la crédibilité du laboratoire. S'assurer d'avoir un site maintenu à flot est donc primordial pour sauvegarder la crédibilité du laboratoire sur le plan scientifique. Cependant, comme mentionné en [introduction au corpus](/index.qmd), un manque de moyen pour s'occuper efficacement de ces tâches semble se faire ressentir à travers de nombreux laboratoires... 

C'est en partant de ce constat que se dessine la première mission du stagiaire : **remettre à niveau et maintenir à jour de façon péreinne les informations liées au laboratoire sur le site internet.** La documentation qui va suivre va revenir sur les différents aspects à aborder pour s'assurer de la réussite de cette mission.

**Durée** :
- à mettre en place : MODERE (Accès aux login peut prendre un certain temps, vérifications peut prendre un peu de temps sans être déraisonnable)
- à maintenir sur le long terme : FACILE (si mise en place d'une stratégie efficace)

## I. Remise à niveau du point de vue de l'information

Il est **recommandé de commencer par cette étape** d'identification des informations à modifier à l'avenir afin d'ensuite pouvoir arriver face aux interfaces avec une idée des modifications à apporter.

### Travail de veille : identifier les informations susceptible d'être obsolètes ou maanquantes

- 1. **Discuter avece le personnel des premiers constats effectués** : Cette première discussion, plutôt à effectuer au début du stage, va permettre au stagiaire d'obtenir une première direction vers où s'orienter dans son travail, en visualisant la charge de travail demandée, le niveau de priorité des différentes modifications à apporter, certaines informations sur le laboratoire ou encore [certains documents contenant des informations utiles qu'il serait pertinent d'exploiter](/web/integ_doc.qmd). 

- 2. **Effectuer soi-même son repérage sur le site web** : Ce repérage que le stagiaire va effectuer soi-même va lui permettre d'approfondir les diverses pistes apportées par la ou les disscussions mentionnées précédemment. Pour se faire, celui-ci doit ***se placer dans la peau d'un visiteur extérieur au laboratoire*** et naviguer rigoureusement dans chacune des rubriques et chaque article du site pour y repérer les coquilles à modifier à postériori tout en s'imprégnant de la structure du site, ce qui est très important pour y apporter les modifications nécessaires par la suite.

Animation simple permettant de voir une simulation de consultation du site web de laboratoire (ici Paragraphe) pour un repérage. ->[Redirection](/assets/img/navigation.gif)

### Contacter les services et personnes pour obtenir les renseignements nécessaires

Certaines informations ne vous seront pas accessibles facilement car trop précises, comme dans le cas d'un projet mené par un(e) enseignant.e-chercheur.euse ou dans le cas d'une biographie par exemple. Ainsi, il ne faut surtout pas hésiter à contacter les personnes concernées pour leur demander des informations où, au minimum, les informer de vous contacter dans le cas où ils voudraient effecteur des modifications. 

### NOTE : Comment afficher l'information pour la rendre lisible sur une page web ?

Parfois, ce ne sont pas les informations qui demandent une correction mais plutôt la façon dont celles-ci sont présentées.

[insérer gif / image ?]

Tout comme de gros livres denses et mal présentés peuvent freiner voire repousser le lecteur, une information ou une page web mal éditorialisée sur le plan visuel peut constituer un frein significatif à la navigation sur le site. De longues pages de texte denses nuisent à la compréhension et à l’attention du lecteur. L’objectif a donc été de structurer les contenus en diverses parties voire en divers articles, d’insérer des titres et sous-titres explicites, d’aérer les paragraphes et, autant que possible, d’intégrer des éléments visuels (liens, images, documents téléchargeables) pour rendre la navigation et la lecture plus dynalique.

(exemples)

Conseil : faire ce travail d'éditorialisation du contenu sur Word, pour se donner les bonnes habitudes (sélection des bons niveaux de titrage, ...) 

## Remise à niveau du point de vue technique

Il est **recommandé de réserver l'utilisation du ou des outils d'administration du site web au moment où le travail de repérage a été effectué**, afin de fluidifier le processus de mise à jour. En effet, avoir une "liste" des informations à changer à tels endroits est plus optimale que de naviguer dans l'arborescence pour vérifier chacuns des articles (risque de se perdre, processus long, ...).

### Collaboration avec l'équipe de webmaster de Paris 8
/** Insertion/suggestion de nouveaux plugins, explication du fonctionnement du site, ... **/

En fonction de là où est hébergé le site du laboratoire et avec quelle CMS celui-ci est administré (WordPress, [SPIP](/tools/intro_spip.qmd), ...), il peut être pertinent de se tourner vers l'équipe de webmastering de l'Université, ne serait-ce que pour se renseigner sur le rôle de ces derniers dans la gestion dudit site. En effet, comme évoqué en [introduction](/index.qmd), l'équipe de webmastering de l'Université Paris 8 peut être amené à s'occuper également des sites de laboratoires si ceux-ci sont hébergés au sein de l'université (comme pour celui de Paragraphe, par exemple). Et comme également mentionné en [introduction](/index.qmd), le but n'est pas de les remplacer mais bien de les assister. **Une prise de contact avec eux est donc vivement recommandée afin de pouvoir réfléchir aux travaux à effectuer (installation de plugin, mise à jour du site, ...).

**Exemple des travaux effectués sur le site du Laboratoire Paragraphe** :

[insérer images & explications]

### Remettre à niveau le site par différents moyens
Une fois que l'on commence à être à l'aise l’aise avec l’architecture du site et l’[usage de SPIP](../tools/intro_spip.qmd), la partie technique peut commencer. 

**Mise à jour des informations** :
Les mettre à jour, les adapter, réfléchir à comment archiver les anciennes informations, ...

**Ajouter de l'hyptextualisation au site** : 
renforcer la cohérence interne du site en ajoutant des liens entre pages, en reliant les contenus entre eux (par exemple : projets ↔ publications ↔ membres)

**Reflechir vis-à-vis de l'ajout de fonctionnalités** :
Via des plugins par exemple

## III. Assurer une maintenance continue

Ce travail de veille peut aussi servir à trouver un certain nombre d'outils pour effectuer ledit repérage, comme [Hypothes.is](../tools/intro_hypothesis.qmd).